### ISSUE TITLE
Use `brew install --cask` instead of `brew cask install`

### ISSUE THREAD

**Issue by ChrisCarini** [ChrisCarini/dotfiles#26]
During post-installation:
```
--------------------
> Installing XQuartz
--------------------
Error: Calling brew cask install is disabled! Use brew install [--cask] instead.
```

**Comment by barskhianfannie** [comment]
This issue still exists for me ? I am unable to run brew cask install java or brew install -cask java to download java to my machine ? Any advice on next steps I can take to resolve this ?

**Comment by ChrisCarini** [comment]
Hi @barskhianfannie - I'd suggest searching for instructions on how to install java via brew if that is something you want to do, otherwise I'd suggest installing it manually from a JDK provider like OpenJDK or Oracle.
